import { ComponentSchema } from "@/types"
import { BasicBlocks, ProductBlocks, Sections } from "./enums"

import {
  BUTTON_SCHEMA,
  GROUP_SCHEMA,
  PRODUCT_FEATURE_SCHEMA,
  SPACER_SCHEMA,
  HEADER_SCHEMA,
  FOOTER_SCHEMA,
  HERO_SECTION_SCHEMA,
  RICH_TEXT_SCHEMA,
  SUBSCRIPTION_FORM_SCHEMA,
  TEXT_SCHEMA,
  IMAGE_SCHEMA,
  PRODUCT_DETAILS_SCHEMA,
  PRODUCT_TITLE_SCHEMA,
  PRODUCT_PRICE_SCHEMA,
  PRODUCT_DESCRIPTION_SCHEMA,
  PRODUCT_ADD_TO_CART_BUTTON_SCHEMA,
  PRODUCT_GALLERY_SCHEMA,
} from "../components"

export const COMPONENTS_SCHEMAS: Record<string, ComponentSchema> = {
  [Sections.HEADER]: HEADER_SCHEMA,
  [Sections.FOOTER]: FOOTER_SCHEMA,
  [Sections.HERO_SECTION]: HERO_SECTION_SCHEMA,
  [Sections.PRODUCT_FEATURES]: PRODUCT_FEATURE_SCHEMA,
  [Sections.RICH_TEXT]: RICH_TEXT_SCHEMA,
  [Sections.SUBSCRIPTION_FORM]: SUBSCRIPTION_FORM_SCHEMA,

  [BasicBlocks.TEXT]: TEXT_SCHEMA,
  [BasicBlocks.BUTTON]: BUTTON_SCHEMA,
  [BasicBlocks.SPACER]: SPACER_SCHEMA,
  [BasicBlocks.GROUP]: GROUP_SCHEMA,
  [BasicBlocks.IMAGE]: IMAGE_SCHEMA,

  [ProductBlocks.PRODUCT_DETAILS_SECTION]: PRODUCT_DETAILS_SCHEMA,
  [ProductBlocks.PRODUCT_TITLE]: PRODUCT_TITLE_SCHEMA,
  [ProductBlocks.PRODUCT_PRICE]: PRODUCT_PRICE_SCHEMA,
  [ProductBlocks.PRODUCT_DESCRIPTION]: PRODUCT_DESCRIPTION_SCHEMA,
  [ProductBlocks.PRODUCT_ADD_TO_CART_BUTTON]: PRODUCT_ADD_TO_CART_BUTTON_SCHEMA,
  [ProductBlocks.PRODUCT_GALLERY]: PRODUCT_GALLERY_SCHEMA,
}
