import { PageSchema } from "@/types"
import {
  BasicBlocks,
  Layouts,
  ProductBlocks,
  CategoryBlocks,
  Sections,
  TemplateUI,
} from "./enums"

export const PAGE_SCHEMAS: Record<string, PageSchema> = {
  [Layouts.HOME]: {
    type: "flexible",
    name: "Homepage",
    canHaveHeader: true,
    canHaveFooter: true,
    allowedSections: [
      Sections.HERO_SECTION,
      Sections.PRODUCT_FEATURES,
      Sections.RICH_TEXT,
      Sections.SUBSCRIPTION_FORM,
      Sections.BANNER,
      BasicBlocks.GROUP,
      TemplateUI.BRAND_FEATURES,
      TemplateUI.BEST_COMMENTS,
      TemplateUI.BLOG_FEATURES,
      BasicBlocks.SPACER,
      BasicBlocks.TAB,
    ],
  },
  [Layouts.PRODUCT]: {
    type: "fixed",
    name: "ProductPage",
    canHaveHeader: true,
    canHaveFooter: true,
    allowedSections: [
      { type: ProductBlocks.PRODUCT_GALLERY, max: 1 },
      { type: ProductBlocks.PRODUCT_DETAILS_SECTION, max: 1 },
      { type: Sections.RICH_TEXT },
      { type: Sections.SUBSCRIPTION_FORM },
      { type: Sections.PRODUCT_FEATURES },
      { type: ProductBlocks.PRODUCT_INFO_TABLE, max: 1 },
      { type: ProductBlocks.PRODUCT_INFO_DESCRIPTION, max: 1 },
      { type: ProductBlocks.PRODUCT_COMMENTS, max: 1 },
      TemplateUI.BRAND_FEATURES,
      BasicBlocks.SPACER,
      BasicBlocks.TAB,
      BasicBlocks.GROUP,
    ],
  },
  [Layouts.USER_PAGES]: {
    type: "flexible",
    name: "Pages",
    allowedSections: [
      Sections.BANNER,
      Sections.HERO_SECTION,
      Sections.PRODUCT_FEATURES,
      Sections.RICH_TEXT,
      Sections.SUBSCRIPTION_FORM,
      TemplateUI.BEST_COMMENTS,
      TemplateUI.BLOG_FEATURES,
      TemplateUI.BRAND_FEATURES,
      BasicBlocks.IMAGE,
      BasicBlocks.SPACER,
      BasicBlocks.GROUP,
      BasicBlocks.HEADING,
      BasicBlocks.TEXT,
      BasicBlocks.SPACER,
      BasicBlocks.TAB,
    ],
    canHaveHeader: true,
    canHaveFooter: true,
  },
  [Layouts.CART]: {
    name: "CART",
    type: "flexible",
    allowedSections: [
      TemplateUI.BRAND_FEATURES,
      BasicBlocks.IMAGE,
      BasicBlocks.SPACER,
      BasicBlocks.GROUP,
      BasicBlocks.HEADING,
      BasicBlocks.TEXT,
      Sections.BANNER,
      Sections.HERO_SECTION,
      Sections.RICH_TEXT,
      Sections.PRODUCT_FEATURES,
      BasicBlocks.APP_COMPONENT_SLOT,
      BasicBlocks.SPACER,
      BasicBlocks.TAB,
    ],
    canHaveHeader: true,
    canHaveFooter: true,
  },
  [Layouts.PRODUCT_LIST]: {
    name: "PRODUCT_LIST",
    type: "flexible",
    allowedSections: [
      TemplateUI.BRAND_FEATURES,
      BasicBlocks.IMAGE,
      BasicBlocks.SPACER,
      BasicBlocks.GROUP,
      BasicBlocks.HEADING,
      BasicBlocks.TEXT,
      Sections.BANNER,
      Sections.HERO_SECTION,
      Sections.RICH_TEXT,
      Sections.PRODUCT_FEATURES,
      { type: CategoryBlocks.PRODUCT_GRID_LIST, max: 1 },
      { type: CategoryBlocks.PRODUCT_FILTERS, max: 1 },
      { type: CategoryBlocks.SUB_CATEGORIES, max: 1 },
      { type: CategoryBlocks.SEO_BOX, max: 1 },
      { type: CategoryBlocks.TITLE, max: 1 },
      BasicBlocks.SPACER,
      BasicBlocks.TAB,
    ],
    canHaveHeader: true,
    canHaveFooter: true,
  },
  [Layouts.SEARCH]: {
    name: "SEARCH",
    type: "flexible",
    allowedSections: [
      TemplateUI.BRAND_FEATURES,
      BasicBlocks.IMAGE,
      BasicBlocks.SPACER,
      BasicBlocks.GROUP,
      BasicBlocks.HEADING,
      BasicBlocks.TEXT,
      Sections.BANNER,
      Sections.HERO_SECTION,
      Sections.RICH_TEXT,
      Sections.PRODUCT_FEATURES,
      BasicBlocks.SPACER,
      BasicBlocks.TAB,
    ],
    canHaveHeader: true,
    canHaveFooter: true,
  },
}
