import { ComponentSchema } from "@/types"
import { BasicBlocks, Layouts, ProductBlocks, Sections } from "./enums"
import {
  GalleryVerticalIcon,
  ImageIcon,
  MonitorIcon,
  SquareMousePointerIcon,
  TextIcon,
  TypeIcon,
} from "lucide-react"
import { ALL_PAGES } from "./groups"

export const COMPONENTS_SCHEMAS: Record<string, ComponentSchema> = {
  [Sections.HEADER]: {
    type: Sections.HEADER,
    label: "Header Section",
    icon: GalleryVerticalIcon,
    allowedChildren: [BasicBlocks.HEADING, BasicBlocks.TEXT],
    allowedParents: [Layouts.HEADER],
    category: "section",
    defaultSettings: [],
    isDraggable: true,
    isDeletable: false,
    isHidable: false,
  },

  [Sections.FOOTER]: {
    type: Sections.FOOTER,
    icon: GalleryVerticalIcon,
    label: "Footer Section",
    allowedChildren: [
      BasicBlocks.BUTTON,
      BasicBlocks.HEADING,
      BasicBlocks.TEXT,
      BasicBlocks.IMAGE,
    ],
    allowedParents: [Layouts.FOOTER],
    category: "section",
    defaultSettings: [],
    isDraggable: true,
    isDeletable: false,
    isHidable: false,
  },

  [Sections.HERO_SECTION]: {
    icon: MonitorIcon,
    type: Sections.HERO_SECTION,
    label: "Hero Section",
    category: "section",
    isDraggable: true,
    allowedParents: [...ALL_PAGES],
    allowedChildren: [
      BasicBlocks.HEADING,
      BasicBlocks.TEXT,
      BasicBlocks.BUTTON,
      BasicBlocks.IMAGE,
    ],
    defaultSettings: [
      {
        key: "backgroundColor",
        label: "Background Color",
        type: "color",
        defaultValue: "#ffffff",
        section: "general",
      },
      {
        key: "textAlignment",
        label: "Text Alignment",
        type: "select",
        defaultValue: "center",
        section: "general",
        options: [
          { label: "Left", value: "left" },
          { label: "Center", value: "center" },
          { label: "Right", value: "right" },
        ],
      },
      {
        key: "padding",
        label: "Padding",
        type: "select",
        defaultValue: "large",
        section: "general",
        options: [
          { label: "Small", value: "small" },
          { label: "Medium", value: "medium" },
          { label: "Large", value: "large" },
        ],
      },
      {
        key: "layout",
        label: "Layout",
        type: "select",
        defaultValue: "stacked",
        section: "general",
        options: [
          { label: "Stacked", value: "stacked" },
          { label: "Side by Side", value: "split" },
        ],
      },
      {
        key: "mobileLayout",
        label: "Mobile Layout",
        type: "select",
        defaultValue: "stacked",
        section: "mobile",
        options: [
          { label: "Stacked", value: "stacked" },
          { label: "Image First", value: "image-first" },
        ],
      },
    ],
  },

  [Sections.PRODUCT_FEATURES]: {
    type: Sections.PRODUCT_FEATURES,
    icon: GalleryVerticalIcon,
    label: "Product Features",
    category: "section",
    isDraggable: true,
    allowedParents: [...ALL_PAGES],
    allowedChildren: [BasicBlocks.FEATURE_ITEM],
    defaultSettings: [
      {
        key: "title",
        label: "Section Title",
        type: "text",
        defaultValue: "Why Choose Us?",
        section: "general",
      },
      {
        key: "layout",
        label: "Layout",
        type: "select",
        defaultValue: "grid",
        section: "general",
        options: [
          { label: "Grid", value: "grid" },
          { label: "List", value: "list" },
        ],
      },
      {
        key: "columns",
        label: "Columns",
        type: "range",
        defaultValue: 3,
        section: "general",
        step: 1,
        min: [1],
        max: [12],
      },
      {
        key: "mobileColumns",
        label: "Mobile Columns",
        type: "select",
        defaultValue: 1,
        section: "mobile",
        options: [
          { label: "1 Column", value: 1 },
          { label: "2 Columns", value: 2 },
        ],
      },
    ],
  },

  [Sections.RICH_TEXT]: {
    type: Sections.RICH_TEXT,
    icon: GalleryVerticalIcon,
    label: "Rich Text",
    category: "section",
    isDraggable: true,
    allowedParents: [...ALL_PAGES],
    allowedChildren: [
      BasicBlocks.HEADING,
      BasicBlocks.IMAGE,
      BasicBlocks.BUTTON,
      BasicBlocks.TEXT,
    ],
    defaultSettings: [
      {
        key: "direction",
        label: "Direction",
        type: "group",
        section: "general",
        defaultValue: "vertical",
        options: [
          { label: "Vertical", value: "vertical" },
          { label: "Horizontal", value: "horizontal" },
        ],
      },
      {
        key: "width",
        label: "Width",
        type: "group",
        section: "general",
        defaultValue: "hi",
        options: [
          { label: "Page", value: "90%" },
          { label: "Full", value: "100%" },
        ],
      },
      {
        key: "height",
        label: "height",
        type: "select",
        section: "general",
        defaultValue: "100%",
        options: [
          { label: "Auto", value: "auto" },
          { label: "Small", value: "100%" },
          { label: "Medium", value: "200px" },
          { label: "Large", value: "400px" },
          { label: "Fullscreen", value: "100vh" },
        ],
      },
      {
        key: "padding",
        label: "Padding",
        type: "select",
        defaultValue: "20px",
        section: "general",
        options: [
          { label: "Small", value: "20px" },
          { label: "Medium", value: "40px" },
          { label: "Large", value: "100px" },
        ],
      },
    ],
  },

  [Sections.SUBSCRIPTION_FORM]: {
    type: Sections.SUBSCRIPTION_FORM,
    icon: GalleryVerticalIcon,
    label: "Newsletter Subscription",
    category: "section",
    isDraggable: true,
    allowedParents: [...ALL_PAGES],
    allowedChildren: [BasicBlocks.HEADING, BasicBlocks.TEXT],
    defaultSettings: [
      {
        key: "title",
        label: "Form Title",
        type: "text",
        defaultValue: "Subscribe to our newsletter",
        section: "general",
      },
      {
        key: "placeholder",
        label: "Email Placeholder",
        type: "text",
        defaultValue: "Enter your email",
        section: "general",
      },
      {
        key: "buttonText",
        label: "Button Text",
        type: "text",
        defaultValue: "Subscribe",
        section: "general",
      },
      {
        key: "layout",
        label: "Layout",
        type: "select",
        defaultValue: "inline",
        section: "general",
        options: [
          { label: "Inline", value: "inline" },
          { label: "Stacked", value: "stacked" },
        ],
      },
      {
        key: "backgroundColor",
        label: "Background Color",
        type: "color",
        defaultValue: "#f8f9fa",
        section: "general",
      },
      {
        key: "mobileLayout",
        label: "Mobile Layout",
        type: "select",
        defaultValue: "stacked",
        section: "mobile",
        options: [
          { label: "Inline", value: "inline" },
          { label: "Stacked", value: "stacked" },
        ],
      },
    ],
  },

  [BasicBlocks.HEADING]: {
    type: BasicBlocks.HEADING,
    icon: TypeIcon,
    label: "Heading",
    category: "block",
    isDraggable: true,
    allowedParents: [
      Sections.HERO_SECTION,
      Sections.RICH_TEXT,
      Sections.SUBSCRIPTION_FORM,
    ],
    allowedChildren: [],
    defaultSettings: [
      {
        key: "text",
        label: "Heading Text",
        type: "text",
        defaultValue: "Your Heading Here",
        section: "general",
      },
      {
        key: "level",
        label: "Heading Level",
        type: "select",
        defaultValue: "h2",
        section: "general",
        options: [
          { label: "H1", value: "h1" },
          { label: "H2", value: "h2" },
          { label: "H3", value: "h3" },
          { label: "H4", value: "h4" },
        ],
      },
      {
        key: "color",
        label: "Text Color",
        type: "color",
        defaultValue: "#333333",
        section: "general",
      },
      {
        key: "fontWeight",
        label: "Font Weight",
        type: "select",
        defaultValue: "bold",
        section: "general",
        options: [
          { label: "Normal", value: "normal" },
          { label: "Medium", value: "medium" },
          { label: "Bold", value: "bold" },
        ],
      },
      {
        key: "mobileLevel",
        label: "Mobile Level",
        type: "select",
        defaultValue: "h3",
        section: "mobile",
        options: [
          { label: "H2", value: "h2" },
          { label: "H3", value: "h3" },
          { label: "H4", value: "h4" },
        ],
      },
    ],
  },

  [BasicBlocks.TEXT]: {
    type: BasicBlocks.TEXT,
    icon: TextIcon,
    label: "Text",
    category: "block",
    isDraggable: true,
    allowedParents: [
      Sections.HERO_SECTION,
      Sections.RICH_TEXT,
      Sections.SUBSCRIPTION_FORM,
      Sections.PRODUCT_FEATURES,
      BasicBlocks.FEATURE_ITEM,
    ],
    allowedChildren: [],
    defaultSettings: [
      {
        key: "content",
        label: "Text Content",
        type: "textarea",
        defaultValue: "Your text content here...",
        section: "general",
      },
      {
        key: "fontSize",
        label: "Font Size",
        type: "select",
        defaultValue: "medium",
        section: "general",
        options: [
          { label: "Small", value: "small" },
          { label: "Medium", value: "medium" },
          { label: "Large", value: "large" },
        ],
      },
      {
        key: "color",
        label: "Text Color",
        type: "color",
        defaultValue: "#666666",
        section: "general",
      },
      {
        key: "lineHeight",
        label: "Line Height",
        type: "select",
        defaultValue: "normal",
        section: "general",
        options: [
          { label: "Tight", value: "tight" },
          { label: "Normal", value: "normal" },
          { label: "Relaxed", value: "relaxed" },
        ],
      },
    ],
  },

  [BasicBlocks.BUTTON]: {
    type: BasicBlocks.BUTTON,
    icon: SquareMousePointerIcon,
    label: "Button",
    category: "block",
    isDraggable: true,
    allowedParents: [Sections.HERO_SECTION, Sections.RICH_TEXT],
    allowedChildren: [],
    defaultSettings: [
      {
        key: "text",
        label: "Button Text",
        type: "text",
        defaultValue: "Click Here",
        section: "general",
      },
      {
        key: "url",
        label: "Link URL",
        type: "text",
        defaultValue: "#",
        section: "general",
      },
      {
        key: "style",
        label: "Button Style",
        type: "select",
        defaultValue: "primary",
        section: "general",
        options: [
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
          { label: "Outline", value: "outline" },
        ],
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        defaultValue: "md",
        section: "general",
        options: [
          { label: "Small", value: "sm" },
          { label: "Medium", value: "md" },
          { label: "Large", value: "lg" },
        ],
      },
      {
        key: "mobileFullWidth",
        label: "Full Width on Mobile",
        type: "boolean",
        defaultValue: false,
        section: "mobile",
      },
    ],
  },

  [BasicBlocks.IMAGE]: {
    type: BasicBlocks.IMAGE,
    icon: ImageIcon,
    label: "Image",
    category: "block",
    isDraggable: true,
    allowedParents: [Sections.HERO_SECTION, Sections.RICH_TEXT],
    allowedChildren: [],
    defaultSettings: [
      {
        key: "src",
        label: "Image URL",
        type: "image",
        defaultValue: "",
        section: "general",
      },
      {
        key: "alt",
        label: "Alt Text",
        type: "text",
        defaultValue: "",
        section: "general",
      },
      {
        key: "width",
        label: "Width",
        type: "select",
        defaultValue: "auto",
        section: "general",
        options: [
          { label: "Auto", value: "auto" },
          { label: "25%", value: "25%" },
          { label: "50%", value: "50%" },
          { label: "75%", value: "75%" },
          { label: "100%", value: "100%" },
        ],
      },
      {
        key: "borderRadius",
        label: "Border Radius",
        type: "select",
        defaultValue: "none",
        section: "general",
        options: [
          { label: "None", value: "none" },
          { label: "Small", value: "small" },
          { label: "Medium", value: "medium" },
          { label: "Large", value: "large" },
          { label: "Full", value: "full" },
        ],
      },
    ],
  },

  [BasicBlocks.FEATURE_ITEM]: {
    type: BasicBlocks.FEATURE_ITEM,
    label: "Feature Item",
    category: "block",
    isDraggable: true,
    allowedParents: [Sections.PRODUCT_FEATURES],
    allowedChildren: [BasicBlocks.TEXT, BasicBlocks.IMAGE, BasicBlocks.HEADING],
    defaultSettings: [
      {
        key: "title",
        label: "Feature Title",
        type: "text",
        defaultValue: "Feature Title",
        section: "general",
      },
      {
        key: "icon",
        label: "Icon",
        type: "icon",
        defaultValue: "Star",
        section: "general",
      },
      {
        key: "iconColor",
        label: "Icon Color",
        type: "color",
        defaultValue: "#3b82f6",
        section: "general",
      },
    ],
  },

  [ProductBlocks.PRODUCT_DETAILS_SECTION]: {
    type: ProductBlocks.PRODUCT_DETAILS_SECTION,
    label: "Product Details",
    category: "section",
    isDraggable: false,
    isDeletable: false,
    allowedParents: [Layouts.PRODUCT],
    slots: {
      title: {
        component: ProductBlocks.PRODUCT_TITLE,
        isLocked: true,
      },
      price: {
        component: ProductBlocks.PRODUCT_PRICE,
        isLocked: true,
      },
      description: {
        component: ProductBlocks.PRODUCT_DESCRIPTION,
        isLocked: true,
        settings: [
          {
            key: "showFullDescription",
            type: "boolean",
            label: "Show Full Description by Default",
            defaultValue: false,
          },
        ],
      },
      addToCart: {
        component: ProductBlocks.ADD_TO_CART_BUTTON,
        isLocked: true,
        settings: [
          {
            key: "inStockText",
            label: "In Stock Text",
            type: "text",
            defaultValue: "Add To Cart",
          },
          {
            key: "outStockText",
            label: "Out Stock Text",
            type: "text",
            defaultValue: "Sold Out",
          },
        ],
        action: {
          type: "ADD_TO_CART",
          payload: {
            productSku: "{{product.sku}}",
            quantity: 1,
          },
        },
      },
    },
    allowedChildren: [],
    defaultSettings: [],
  },

  [ProductBlocks.PRODUCT_TITLE]: {
    type: ProductBlocks.PRODUCT_TITLE,
    label: "Product Title",
    category: "block",
    isDraggable: true,
    isDeletable: false,
    allowedParents: [ProductBlocks.PRODUCT_DETAILS_SECTION],
    allowedChildren: [],
    defaultSettings: [
      {
        key: "tag",
        type: "select",
        label: "HTML Tag",
        defaultValue: "h1",
        options: [
          { label: "H1", value: "h1" },
          { label: "H2", value: "h2" },
        ],
      },
    ],
  },

  [ProductBlocks.PRODUCT_PRICE]: {
    type: ProductBlocks.PRODUCT_PRICE,
    label: "Product Price",
    category: "block",
    isDraggable: true,
    isDeletable: false,
    allowedParents: [ProductBlocks.PRODUCT_DETAILS_SECTION],
    allowedChildren: [],
    defaultSettings: [],
  },

  [ProductBlocks.PRODUCT_DESCRIPTION]: {
    type: ProductBlocks.PRODUCT_DESCRIPTION,
    label: "PRODUCT_DESCRIPTION",
    category: "block",
    isDraggable: true,
    isDeletable: false,
    allowedParents: [ProductBlocks.PRODUCT_DETAILS_SECTION],
    allowedChildren: [],
    defaultSettings: [],
  },

  [ProductBlocks.ADD_TO_CART_BUTTON]: {
    type: ProductBlocks.ADD_TO_CART_BUTTON,
    label: "Add to Cart Button",
    category: "block",
    isDraggable: true,
    isDeletable: false,
    allowedParents: [ProductBlocks.PRODUCT_DETAILS_SECTION],
    allowedChildren: [],
    defaultSettings: [],
  },

  [ProductBlocks.PRODUCT_GALLERY]: {
    type: ProductBlocks.PRODUCT_GALLERY,
    label: "PRODUCT_GALLERY",
    category: "section",
    isDraggable: false,
    isDeletable: false,
    allowedParents: [Layouts.PRODUCT],
    allowedChildren: [],
    defaultSettings: [
      {
        key: "thumbnailPosition",
        type: "select",
        label: "Thumbnail Position",
        defaultValue: "bottom",
        options: [
          { label: "Bottom", value: "bottom" },
          { label: "Left", value: "left" },
        ],
      },
    ],
  },
}
